name: gh-release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: read changelog
        id: changelogReader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }}
          path: docs/changelog.md

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelogReader.outputs.changes }}
          name: '${{ github.ref_name }}'
